# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [4]:
import torch

tensor_A = torch.rand(7, 7)
print(tensor_A)
print("Shape:", tensor_A.shape)



tensor([[0.9534, 0.4683, 0.4129, 0.1410, 0.3080, 0.3043, 0.8881],
        [0.8990, 0.2177, 0.1669, 0.1762, 0.0321, 0.4155, 0.4684],
        [0.6138, 0.4248, 0.9503, 0.3099, 0.7021, 0.1336, 0.4175],
        [0.0224, 0.0468, 0.5552, 0.1030, 0.4487, 0.1616, 0.0044],
        [0.0234, 0.7155, 0.3317, 0.3161, 0.4596, 0.7032, 0.4293],
        [0.1699, 0.2798, 0.7801, 0.8917, 0.4354, 0.6969, 0.5717],
        [0.9063, 0.6264, 0.4484, 0.6480, 0.3078, 0.9555, 0.0575]])
Shape: torch.Size([7, 7])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [5]:

tensor_B = torch.rand(1, 7)
result = torch.matmul(tensor_A, tensor_B.T)  
print(result)
print("Shape:", result.shape)



tensor([[1.7206],
        [1.0101],
        [1.8520],
        [0.7087],
        [1.4635],
        [1.9622],
        [1.6235]])
Shape: torch.Size([7, 1])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [6]:

torch.manual_seed(0)


tensor_A = torch.rand(7, 7)
tensor_B = torch.rand(1, 7)

result = torch.matmul(tensor_A, tensor_B.T)
print(result, result.shape)



tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]) torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [7]:

torch.cuda.manual_seed(1234)




### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [8]:

torch.manual_seed(1234)


device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)


tensor_A = torch.rand(2, 3).to(device)
tensor_B = torch.rand(2, 3).to(device)

print(tensor_A)
print(tensor_B)


Device: cpu
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]])



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [9]:

result = torch.matmul(tensor_A, tensor_B.T)
print(result, result.shape)



tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]]) torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [10]:
print("Max value:", result.max())
print("Min value:", result.min())



Max value: tensor(0.5617)
Min value: tensor(0.3647)


### 9. Find the maximum and minimum index values of the output of 7.

In [11]:
print("Index of max:", torch.argmax(result))
print("Index of min:", torch.argmin(result))


Index of max: tensor(3)
Index of min: tensor(0)



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [12]:

torch.manual_seed(7)

tensor = torch.rand(1, 1, 1, 10)
print(tensor, tensor.shape)


squeezed = tensor.squeeze()
print(squeezed, squeezed.shape)



tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
